In [2]:
#Array creation
# 1. Create a numpy array of size 10, filled with zeros.

import numpy as np
zeros_array = np.zeros(10)
print(zeros_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
# 2. Create a numpy array with values ranging from 10 to 49

import numpy as np
array =np.arange(10,50)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [11]:
# 3. Create a numpy matrix of 2*2 integers, filled with ones.

import numpy as np
matrix_int =  np.ones((2, 2), dtype=int)
print(matrix_int)

[[1 1]
 [1 1]]


In [12]:
# 4. Create a numpy matrix of 3*2 float numbers, filled with ones.

import numpy as np
matrix_float = np.ones((3,2), dtype = float)
print(matrix_float)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [13]:
# 5. Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

import numpy as np
X = np.array([[1, 2, 3], [4, 5, 6]])
ones_like_X = np.ones_like(X)

print(ones_like_X)

[[1 1 1]
 [1 1 1]]


In [16]:
# 6. Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

import numpy as np
X = np.array([[1, 2, 3], [4, 5, 6]])
ones_like_X = np.zeros_like(X)
print(ones_like_X)

[[0 0 0]
 [0 0 0]]


In [19]:
# 7. Create a numpy matrix of 4*4 integers, filled with fives.
import numpy as np
matrix_int =  np.full((4, 4), 5, dtype=int)
print(matrix_int)


[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [22]:
# 8. Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

import numpy as np
matrix_seven = np.full((4,4), 7, dtype=int)
print(matrix_seven)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [24]:
# 9. Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

import numpy as np
matrix_identity = np. eye(3)
print(matrix_identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
# 10. Create a numpy array, filled with 3 random integer values between 1 and 10.

import numpy as np
random_integers = np.random.randint(1, 11, size=3)

print(random_integers)


[8 7 5]


In [29]:
# 11. Create a 3*3*3 numpy matrix, filled with random float values.

import numpy as np
random_float = np.random.rand(3, 3, 3)
print(random_float)

[[[0.47853042 0.20596566 0.33191572]
  [0.36669207 0.22110751 0.4209349 ]
  [0.74627233 0.65932049 0.02945756]]

 [[0.44082051 0.62113234 0.82466586]
  [0.29280737 0.56459477 0.37990626]
  [0.89147709 0.21026058 0.02677481]]

 [[0.00991157 0.33673266 0.62944807]
  [0.52704157 0.98942843 0.3994968 ]
  [0.2829861  0.21257234 0.30414099]]]


In [33]:
# 12. Create a numpy array with numbers from 1 to 10

import numpy as np
array = np. arange (1,11)
print(array)

[ 1  2  3  4  5  6  7  8  9 10]


In [34]:
# 13. Create a numpy array with the odd numbers between 1 to 10

import numpy as np
odd_array = np. arange(1, 11, step=2)
print(odd_array)

[1 3 5 7 9]


In [36]:
# 14. Create a numpy array with numbers from 1 to 10, in descending order.

import numpy as np
des_array = np.arange(10, 0, -1)
print(des_array)

[10  9  8  7  6  5  4  3  2  1]


In [39]:
# 15. Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

import numpy as np
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [43]:
#Array indexation
# 1. Given the X numpy array, show it's first element

import numpy as np

X = np.array([1, 2, 3, 4, 5])
first_element = X[0]
print("First Element =",first_element)

First Element = 1


In [42]:
# 2. Given the X numpy array, show it's last element

import numpy as np
x = np.array([1, 2, 3, 4, 5])
last_element = X[-1]
print("Last Element =",last_element)

Last Element = 5


In [45]:
# 3. Given the X numpy array, show it's first three elements

import numpy as np
x = np.array([1, 2, 3, 4, 5])
First_3_element = X[:3]
print("First Three Elements = ",First_3_element)

First Three Elements =  [1 2 3]


In [47]:
 # 4. Given the X numpy array, show all middle elements

X = np.array([1, 2, 3, 4, 5, 6])
length = len(X)
if length % 2 == 0:
    middle_indices = [length // 2 - 1, length // 2]
else:
    middle_indices = [length // 2]
middle_elements = X[middle_indices]
print("Middle Elements =",middle_elements)

Middle Elements = [3 4]


In [49]:
# 5. Given the X numpy array, show the elements in reverse position.

import numpy as np
X = np.array([1, 2, 3, 4, 5, 6])
reverse_elements = X[::-1]
print("Reverse Position:",reverse_elements)

Reverse Position: [6 5 4 3 2 1]


In [50]:
# 6. Given the X numpy array, show the elements in an odd position.

import numpy as np
X = np.array([1, 2, 3, 4, 5, 6])
odd_position_elements = X[1::2]
print("Odd Position Elements:",odd_position_elements)

Odd Position Elements: [2 4 6]


In [51]:
# 7. Given the X numpy matrix, show the first row elements.

import numpy as np
X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

first_row_elements = X[0, :]
print("First Row=",first_row_elements)

First Row= [1 2 3]


In [52]:
# 8. Given the X numpy matrix, show the last row elements.

import numpy as np
X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

last_row_elements = X[-1, :]
print("Last Row=",last_row_elements)

Last Row= [7 8 9]


In [53]:
# 9. Given the X numpy matrix, show the first element on first row

import numpy as np
X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

first_elements = X[0, 0]
print("First Element=",first_elements)


First Element= 1


In [57]:
# 10. Given the X numpy matrix, show the last element on last row.

import numpy as np
X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

last_elements = X[2, 2]
print("Last Element=",last_elements)


Last Element= 9


In [62]:
# 11. Given the X numpy matrix, show the first two elements on the first two rows.

import numpy as np
X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

First_2_elements = X[:2, :2]
print("First Two Elements=",First_2_elements)



First Two Elements= [[1 2]
 [4 5]]


In [64]:
# 12. Given the X numpy matrix, show the last two elements on the last two rows

import numpy as np
X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

First_2_elements = X[-2:, -2:]
print("First Two Elements=",First_2_elements)


First Two Elements= [[5 6]
 [8 9]]


In [66]:
#Array manipulation
#1. Convert the given integer numpy array to float

import numpy as np
X_integer = np.array([1, 2, 3, 4, 5])
X_float = X_integer.astype(float)
print("Original Integer Array:",(X_integer))
print("\nConverted Float Array:",(X_float))



Original Integer Array: [1 2 3 4 5]

Converted Float Array: [1. 2. 3. 4. 5.]


In [67]:
# 2. Reverse the given numpy array (first element becomes last)

import numpy as np
X = np.array([1, 2, 3, 4, 5])
X_reversed = X[::-1]
print("Original Array:",(X))
print("\nReversed Array:",(X_reversed))


Original Array: [1 2 3 4 5]

Reversed Array: [5 4 3 2 1]


In [68]:
# 3. Given the X numpy array, set the fifth element equal to 1

import numpy as np
X = np.array([2, 4, 6, 7, 3])
X[4] = 1
print("Updated Array:",(X))


Updated Array: [2 4 6 7 1]


In [70]:
# 4. Given the X numpy matrix, change the last row with all 1

import numpy as np
X = np.array([[1,2,3],
             [4,5,6],
            [7,8,9]])
X[0] = [9,10,11]
print("Updated",X)

Updated [[ 9 10 11]
 [ 4  5  6]
 [ 7  8  9]]


In [71]:
# 5. Given the X numpy matrix, add 5 to every element

import numpy as np
X = np.array([[1,2,3],
             [4,5,6],
            [7,8,9]])
X[:,:] = [5]
print("Updated",X)


Updated [[5 5 5]
 [5 5 5]
 [5 5 5]]
